# /kubernetes/apps/default/hajimari/app/helmrelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    
    controller:
      strategy: RollingUpdate
      
    env:
      - name: HAJIMARI_DEFAULT_GROUP
        value: "default"
      
    persistence:
      config:
        enabled: true
        existingClaim: hajimari-config
        
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - network
          - storage
      name: "Home"
      customApps:
        - name: Some Link
          url: "https://example.com"
          icon: "mdi:example"
      
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
    
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
    
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      seccompProfile:
        type: RuntimeDefault