# /kubernetes/apps/default/hajimari/app/pvc.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany  # Changed from ReadWriteOnce to ReadWriteMany for NFS
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi