apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:T+bqoCXNcoXcAj5oHtiiHzM1tiMF6Ed+NAXnmk7qaAISiuEN,iv:29x8A9n07O17swty2QZ86r7gFAJ3asEYlbRqluguNPM=,tag:rM3V6nlzgpjFTZXYMgB0qQ==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:KfA+PvwWCaMN9Y4BySJL0nGkFEg+XUdLelKzOt8jLGiQhgl/PXmpo3rW4rR4UxhtLOJa4jZ0N6zzAsefySBgpCU21nEema+BRubB5xc7C3n2eHr098ZE+h5jAVFEU3tms5/axzyZyoK2/URL2HRFvBtTr+h03SnANmWBp7AlichfKFDmWXeo94Jg0ZzYkfXr0m43FFTf6eFwhefT2GNOTbNPCiby6yXDGyILWa5FeA==,iv:jYjp9Q7AbZer+8ztQWIE97630/xffT63X/+8Co1RgGU=,tag:gJt4yFTN0v1zKleXYnJSbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ejefu6eykz3qan7szqn9399ck48pn5fx5c4h8xaurxmerwgwxesqrv5fzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNkdNRDFsVUg0cjVTQ2xW
            SnV2SFBwM2lvQjF2OFVrU2ZId1A5emxNeUhrClJSU2FDamN1NlZMakkzNncvWkVI
            bzIzZk9Gall2TndLQWcyMWx2cWtRQ2sKLS0tIFBLVzNwQWZYcTNFcmxnekdSNmJX
            SE1sSTllYmw3ZzhOTlpwRzBWVGFhZmsKOQbUcZlQUp7IDDEDTzY7Pvk/G1OqcYDn
            jmI0Lys8JDNbFeiX8LaxUO+QGxpBeEHMd9Xc92yIpUS00qAGjx4W3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T17:53:45Z"
    mac: ENC[AES256_GCM,data:9TjeOYYAucMkT3eyD8Y2tayhcXWRr/oNnHfzdY3z0t2Eve/5QsUHCjEqOVoKZXk65j8z7xNtbI1JM5ZTfgo614y7jebXPAPjRJuksV51U2+81/exmjUTV3ElTeuqSB1j++peHSG6138sBzwzXQAA0OkgQ9fK1/sL5bVR8spj1/8=,iv:TM4FohCql1tKNd3tYb+iK3lJGYRUjd6aYdYxU2y2JlY=,tag:NflIq5Qp57/ugIqyZWLMyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
