apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:qgS6oCLeXT2SAqU1UxZ6f7ILubBbfQvpFPIsPksgtOmOiKfqmhaClQ==,iv:DtH05fp1OiedZrnCvbEkhCz23UV4y7EA8pUrM+u8AfU=,tag:T6PmrkiUpTzbuo5HSPPUfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ht697rvun9tpspg8dc4t63rfv0gcnzpqghedrdsmqf8aqfkhw5hqk5v02x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcFNKZHZwV2N4aHZEYU1X
            YXQrK2N4bHRjcldqdXJ1TDhwbDk3YXVYaVFVClZaTFlWUUtob3BqZHlHYWJPRDdY
            Q1BGQWpDYU84RGF4UTc1c0NLc0grajgKLS0tIHNWV25GSGVaREFhZTJsQjdZZHRv
            cXZMZzByRXR1VFdCZzhhcys3WW0vY1kKC7l7REUNKeKPiVXuHCVgpiiaOprWpbGf
            ZFFBf7lx77s5OFfaGjb7GVVL56Yy2hAk6HGxY8u4cnu6YMTUgYrJzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T16:31:20Z"
    mac: ENC[AES256_GCM,data:7FENb36VBMyeCS2A7VJg/M5aF1K8Y5pPMmUshAZlyRJ6aHM2GZOLD5h5B5eUHc7y3C8OT+YdW6ZlW5tMKVmGfEAAnwccyf/kT5yj3usBwyQtrVvvT00ja2mprLNPgYgL0eALRyLmnRxPYGWbXe2Ial2NQO25LT4IrrULBTTQZJs=,iv:FM6b83Tx2X2O3Ds2F/kEmCje5E4lB6SRRnnR6YAvc9Y=,tag:iE+4m8FCvEdylJNGqos2Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
