apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:U0Kddz/wn+b9IFEqUkj/SJ0sCANpCVWYAgyXkIqCFAsFpGctnWZl2Q==,iv:7drL8BM4GBcyeOz193U/Kgunp+Wkp+DUA0ZaMbLIQ34=,tag:LZxY0jVEi3x6BUvkk8fTCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ejefu6eykz3qan7szqn9399ck48pn5fx5c4h8xaurxmerwgwxesqrv5fzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwczNVSEY1ZlQ5NVhqeXFC
            RTRPM1ZWOHQxZXpnRDA4ODB5R2dGdEpja3hnCjFyRHRtdFQvOVAvYjdMdkxjY2JM
            N2xRdE9ibXJHazJOMDNGRDZQRCtHQVEKLS0tIGc1TktkNCtRa2d6Y2MvVEJGY3dI
            dzBvSjQ1VzhGTk9hYk81Y3Nhbm9JTjQKr0Hu+c9/+4th+NyVeUuP4EyTOii/bSI5
            lR0zPhLtsqLY6dVNAujUBtBHF8TYcTytT5i4G5cidcCnba1CjlgKEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T17:53:45Z"
    mac: ENC[AES256_GCM,data:N4dlYzsk0HvhnNCot5eabb15x2stnjGTEvN3j0N1g+kwscYZhIPBk2KgeAMrZ1QmSA5yORNAHvRQWcKlwsze7h3cZzAXefNiKBaX9wCKnVXGJC+C03qLbx20Xg42M/ZZPkifDP4vo0KEEIWqUHZbKMTp+pFDDrI/ol7tPK/CeT0=,iv:KBp0Fqw50awvmLpISDMzs/vHstsgXk/RHVJCpI9X9NU=,tag:cNsS7Ged8l7f+6TVkLXYaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
