apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GPIybxAO+vaOUZqFoM3KgQ==,iv:XGlhUonmJ8Z8uMrVgRkQ7csJy2qGI5/1m+hMLfWe5xY=,tag:V6S7S9ZBqVCMHy6G3QsHeg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RDGJUdfvkNaNivoadIDa+z0Go1Hi,iv:3ZjeGQlH315hL9ZLyx8QRCtSVf+O7o3MSn5EbLf55tI=,tag:24qSq5axfxcmFqAuh05CAQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:E885aUFp3njIZZgXMvJAeOBYK0zYb4gzuDJSk+N59FN7WsiE,iv:+IsTDmWmfQni2TtZhn9lo6oetd5IVA0//41HX5HqL/M=,tag:BO6TkhZL3Y/x2xRyfspJmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ht697rvun9tpspg8dc4t63rfv0gcnzpqghedrdsmqf8aqfkhw5hqk5v02x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVkUxVkZuTXltNGxSdTQ3
            ZG5zVG9pUEZrZG5pWnpiUjZYS2FmenV1dDNnCjNIa2YzQmE4cHgzQmZIY2F1WXY4
            a0FkTEZqYTc2MkwvSHZMd0dDazVqYlkKLS0tIHBDN0w4UndYWnhnYThqaFRQNjI1
            OEVtczN5M1B5MjdxOVYzeGl0cDIyamMKz67Adbb5n8uvLo/wbbq9VN63ociCl7Zn
            Tyrm4trWNlIziCQS11AZJm/EuXIyjcTINTcRU7go5iXzekTHpcQ55Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T16:31:20Z"
    mac: ENC[AES256_GCM,data:j2tgfOWRpDOAjKGKlM0ekA2dOKEn7TDJG+eaK0biIn82vcEBJvl6pOEUJcp8B/8RGvmLNFG8V+0itc3IpXuMvgxVr85dqt/WQobYmcfpe0qpxYGoNd0V9ilNTpNuQ8X5p+oHQIzNlC+SryeOab2DKQj999uneZyPegw89PLC5oo=,iv:2huQZ2G62WjHabll6Nes6vv7rTfEE6tbkGF3PiaCPto=,tag:xXrRTyMkeLwTdGA2hDDGow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
