apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:8SWGUu+C1IrKCn8rxrdhnRt8kmBcsrJZEmySQ5fPgaty27lH/qDHx0Yx6HP/1O3kv3AMQuaIsnwJvqwtlm8zibeC8VibABybCy5UXearrjtgGYY81DLLfpNh/PH+8w==,iv:XFQG8b3A8mtRqSkiwJlMXU7Fco0eL061O7Il2LrZpNU=,tag:PVGiTAroMHSXyFoG3ebKVA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:9eaYHFzAL3ZtO4sstEXwBQ==,iv:+U7CE2d0c9HEsnFWFcR/ubIc2pjPFM7B3F6hnhcA+P4=,tag:kGtNXEi6OJdbZuKC4DbQnA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZzRf56k+DfZxtxYWRmuGEPkw1F0b,iv:UM/C55yjX8/wtlULR1ZBTP83ZAjCbEBPWa2usiW3yDg=,tag:Sh++irzgA4eFCbz+PEMYuQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NXNi0tmis0/WkyZyy4Kz2+8U7aP6uB4Jcz11mekyz1JD4cgz,iv:NyWJAumRPk0XEB9sd9gPcFKyOmOEeMUmjs5MAbihIDw=,tag:FLXIfV92XwV+k9U23BgTsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ejefu6eykz3qan7szqn9399ck48pn5fx5c4h8xaurxmerwgwxesqrv5fzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb1ZVU01uSElBWnFXVVd0
            Wjlxb3RRaHlxVi9PT200UWZLeXg2VENJZzBnCm5FNGtCNUdzMnZnR29ORlZFKzd4
            SVBCZXFpUUtXUTJodmVpdTBIcDFWNGcKLS0tIGVvSzlCbnQzUTF1NHNoL0JUYzU1
            dW45OTVPdUt1aTYycXpqQmtlc1p6N1UKanaieCz4HPr227ITtLZc7PpeyrIvqr2q
            1V8cF4o1EpoT1jyPMqLOiPZMzsKzWXM0Exymnag6FoNPd6waqOVeTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T17:53:45Z"
    mac: ENC[AES256_GCM,data:FJU5bcMXFuLd2OLiyeZDU5hbxNDclLTuzNXgMXPXcwwaGZkuAwWAdy4+vjm32kWtVBB1SapLeYhPfOLAAWBGXKf1ReLcGwmSwwVTCyn3/RTVdrUtFhHolZtnB7eZGuyIOrlmFchHuPWXi3yCuniXeuOSx+G2oQJn4XPV4T7yBFw=,iv:wLzKSFLx16UpFs0S4eUuKBVOGaPlRqlXVtUsW6k/8zE=,tag:qeJNFSR0QexxR/Szwn9UsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
