apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:QCnZjjO+TnDwGxCZJHcsPMQ4d2FzA9KTlx+Aoalxfvk=,iv:qtUHQA1sHr+qhNbFyWNMKLUCpFR6GwjH4Hqbejc2x5g=,tag:n2B/b/5mc0hEcNDw6BfxDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ejefu6eykz3qan7szqn9399ck48pn5fx5c4h8xaurxmerwgwxesqrv5fzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRDRWNEF0SXZiZGt3N1Yw
            c2IwamNueVR5eTNxTGFJVXpnVmhLOG15WkZNCk1uQ09hRGpuNW4zZ3ByR2p6Yk0w
            ajJQVlRzaVdyNlNuUm5aQjhFc1dEZEUKLS0tIDAzaEY3aWVXUmlGTmFlRDZERzdL
            NU5yQmpkQXN6THNRay9OVGJ5T2FIUzQKKZAK89FmHswmzFie9dvEar/DUiF25NOq
            gO6b5Lz+T9+ICtJMjEVXEH2IiaUCE45oDeivNLRyaTeJCVuM57/RrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T17:53:45Z"
    mac: ENC[AES256_GCM,data:xKsdnP2of7LQa7BYYGltWfTzJ4gz9+VGyleQpKuTvLwrLf3zvfjmeLbNnR4iDeRJnaqJErGYgcQ4M+vd/Z26fDcT+/PCDlJu81ZXcM635lrjh5Ydi6FPmgi6fuQXH28AMV+KdCCVrqcNDjLDC+ISZc4Q1h85JAmmYLT8Oz+L300=,iv:cYN0bJSFETNiujHgbL9ROjrn766WyG6VvG3fLU1/Aoo=,tag:5WY3eQpTFOom5iuoCM+5bQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
