apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:B8tZxb+c7yxNOExY+NGGNqVC9YMfT02qEd1X++6fYM0=,iv:GN9pbdPTCbrs/zy4Y1mYaFt7T9/Btz9DCyq2uV2uzeQ=,tag:hogieA4KnPnZtg4aytzmGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ht697rvun9tpspg8dc4t63rfv0gcnzpqghedrdsmqf8aqfkhw5hqk5v02x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUmxlZ1FUUlVBcitmMHBK
            WnZHZGdxU1liNzZLSnplaDBadE9WMk9kK1cwCkFNOXlNUVFHamxMNmVUcHpGVXFq
            NXZZZHV2RjdpdU83eFc4MHkvemRTWlkKLS0tIE9ieFhzQ0orOFFFNlpMcEV1cWRG
            T1FoT3BjUDdoamxIejNOc2dsb1FRYkUKuAGPwZm5u1kJ6M9G7eDP+H4P4Hsy7DwQ
            /j2rQ0LgpvYkaiK2ZHWuS27b4F1oUWLA+YUEA6Pzxyy3rinoP+6yCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T16:31:20Z"
    mac: ENC[AES256_GCM,data:6Fz+AiX1hstkmxis6oL7171/lvjqyjJsHTUO9n/HNkfLSVEkQP0thOjknkHLGOsdnbwLZg10jRa9pY1X511lGEwhm84HKYTZGmt0XY9OKBui6hQbmFIXoIfbdVoJI5/GFVUOCm0ZIVBUmyfx7lo0L5ZA/kIq2GNnG5S41YggcOk=,iv:Jm3nJwGGi4ESHrAoVTm94xhnyDKz1mUmUkIvtDroCzQ=,tag:THvkmG4StBs6Y/Byg8vQHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
