apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:jv+XHhW7Ye55cKj3eap9tZTnRL1tZhRAVYabHlC3qj2QOIhKnYMFlQ==,iv:xdk1ZyLEVynaU5KRgfvoTsGbLGB9RywIcNE0L0kIYkM=,tag:vvCjnnTOxrA1SCMKJlP/ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ejefu6eykz3qan7szqn9399ck48pn5fx5c4h8xaurxmerwgwxesqrv5fzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMjZNV3hTQWJxdU1ieERw
            Z2VsR2xjYkNVbDdGYWI0NnF5dmk2ZTJ5bFJFCnc2Z1daSXRoNFVCZzRLRi96RzNB
            SmdJb29IRjJzbEVqbkN4YlgzVzhRSmMKLS0tIFZTanNvdTc2Sm11bUl0cXRaVHVU
            b3RPcDZaM2l5aHRhNEhGSlR2elJnSDAKUskZJkh6YvN5LEnKxr+7rlqrTI+653Rv
            SwAHNa+jbliAeqmBQXlBC/5vd4AIi5UTjnigMzWgaTkIJqgMtiAhCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T17:53:45Z"
    mac: ENC[AES256_GCM,data:A6M2mjqExGyFH3uQIKRwAMowvmmUM8LIriYVEwRzoJIKOuk+UW6c/pqd9Hd1opW/XgpePeQV+6dP4anI0ZIMSC/Ty+j10M8ABRGx1IyrlGt4ySmAWSLzRFyWDmUa2yKFU7dAAOtb8ke4j4cbWu3PUeSKdZaFaq6l3bku8CehfCk=,iv:oWD7LSCzHNIXzY0lsqbMuWiW4za7Y4N8zKREpNiusfQ=,tag:1TuRNwANuaPDc+49LGoGJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
